### ISSUE TITLE
Pull Request format and GitHub template (ADR0009)

### ISSUE THREAD

**Issue by timgentry** [HealthDataInsight/way_of_working#48]
## Context and Problem Statement

The structure of a Pull Request (PR) can take many forms, making it difficult to understand at a glance the what, why and how of a PR. Which form should we choose?

Whichever format is chosen, we should create an initialiser to add the GitHub [PR template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) to a project.

## Considered Options

* Formless – No conventions for PR format and structure
* [What? Why? How? Testing? Screenshots (optional) Anything Else?](https://www.pullrequest.com/blog/writing-a-great-pull-request-description/)
* {title of option 2}
* {title of option 3}

**Comment by timgentry** [comment]
@ollietulloch are there any other templates you've looked at using?

**Comment by ollietulloch** [comment]
Hi @timgentry, I also looked at the below, but settle on What? Why? etc

https://axolo.co/blog/p/part-3-github-pull-request-template
https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/
https://maddevs.io/blog/how-to-make-a-proper-description-for-a-pull-request/

**Comment by timgentry** [comment]
> Hi @timgentry, I also looked at the below, but settle on What? Why? etc
> 
> https://axolo.co/blog/p/part-3-github-pull-request-template https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/ https://maddevs.io/blog/how-to-make-a-proper-description-for-a-pull-request/

Thanks @ollietulloch

**Comment by timgentry** [comment]
Remaining tasks:

- [ ] Create the Thor Initialiser to copy the template to `.github/PULL_REQUEST_TEMPLATE/`
- [ ] Add the documentation page explaining why it's useful and how to add it to a project
